// Re-export everything from webStorage (works on all platforms including web)
export {
    initDatabase,
    getDatabase,
    resetDatabase,
    getAllTransactions,
    getTransactionsByDateRange,
    getTransactionsByMonth,
    addTransaction,
    updateTransaction,
    deleteTransaction,
    getAllCategories,
    getCategoriesByType,
    addCategory,
    getAllAccounts,
    addAccount,
    deleteAccount,
    updateAccountBalance,
    updateAccount,
    getTransactionsByAccount,
    getMonthlyStats,
    // Recurring Transactions
    getAllRecurringTransactions,
    addRecurringTransaction,
    updateRecurringTransaction,
    deleteRecurringTransaction,
    toggleRecurringTransaction,
    // Goals
    getAllGoals,
    addGoal,
    updateGoal,
    deleteGoal,
    addGoalDeposit,
    getActiveGoals,
} from './webStorage';
